# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaah < Formula
  desc "Yet Another Agent Harness — Go toolkit for managing Claude Code configuration"
  homepage "https://github.com/dirien/yet-another-agent-harness"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.2/yet-another-agent-harness_darwin_amd64.tar.gz"
      sha256 "69dcb9a944a3b7b213df6d6bfde2b24efc6346a8b5566dc7342f0301a04ec0e2"

      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.2/yet-another-agent-harness_darwin_arm64.tar.gz"
      sha256 "0ce6e15eaa8a4c272fd6bba5ee03267c3879bca941a09996d10181631327d829"

      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.2/yet-another-agent-harness_linux_amd64.tar.gz"
      sha256 "5cedc377712138d46bd14e623b0fb30bb89cb899d256f23af2d1016ebeca72e8"
      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.2/yet-another-agent-harness_linux_arm64.tar.gz"
      sha256 "d303710368cb0bf27a3f40e185b8a74fc95f0ec6b80e7ab5f93a3a6470c1a699"
      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  test do
    system "#{bin}/yaah", "--help"
  end
end
