# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaah < Formula
  desc "Yet Another Agent Harness — Go toolkit for managing Claude Code configuration"
  homepage "https://github.com/dirien/yet-another-agent-harness"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.1.0/yet-another-agent-harness_darwin_amd64.tar.gz"
      sha256 "9c36a0370a9de996c16a4da0a118283cffe8e4ff17246684af0f5e720613bb03"

      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.1.0/yet-another-agent-harness_darwin_arm64.tar.gz"
      sha256 "7d9510c9496b605071efc8201e0472166286568126c176dc2dcf1b8fb252c1b1"

      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.1.0/yet-another-agent-harness_linux_amd64.tar.gz"
      sha256 "fb88802b4f9deb165ae3d20c4ad592b8a7265e0eb9db77b55590f8b29c15f582"
      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.1.0/yet-another-agent-harness_linux_arm64.tar.gz"
      sha256 "8df435c4847b2ad1073dff7a0c94b405943468537b1684999c68d8b124e9c0fd"
      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  test do
    system "#{bin}/yaah", "--help"
  end
end
