# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaah < Formula
  desc "Yet Another Agent Harness — Go toolkit for managing Claude Code configuration"
  homepage "https://github.com/dirien/yet-another-agent-harness"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.4/yet-another-agent-harness_darwin_amd64.tar.gz"
      sha256 "d1a94c73809cfa8ae9516a6f4ace1926b7d16158357e2008ca947662f60dddab"

      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.4/yet-another-agent-harness_darwin_arm64.tar.gz"
      sha256 "60d23a088b87d8cf163dcba0a9009925dcc2cf1d13544d5e2538ed8d6dc8d90a"

      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.4/yet-another-agent-harness_linux_amd64.tar.gz"
      sha256 "ac77fca3811ba1cc75e655ef7c41d16456fe808b1dfb034d3c75ff6aa7af983a"
      define_method(:install) do
        bin.install "yaah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/yet-another-agent-harness/releases/download/v0.3.4/yet-another-agent-harness_linux_arm64.tar.gz"
      sha256 "059b473b548a38d67198edcbb2f14ec737765881f38f2ecc1e1b62f93a756ae4"
      define_method(:install) do
        bin.install "yaah"
      end
    end
  end

  test do
    system "#{bin}/yaah", "--help"
  end
end
